function change_gene_symbols_individual_MG133(MarkerSize, FontSize, MultiCol)
% ChangeGeneSymbols(MarkerSize, FontSize, nPerCol);
%
% changes gene symbols so in situ plots look nice. 
% MarkerSize defaults to 6 - if 0, won't change existing sizes
%
% FontSize is font size for legend
%
% nPerCol says how many legend entries per column (0 for one-column)
% 
% Kenneth D. Harris, 29/3/17
% GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.en.html
 
if nargin<1 || isempty(MarkerSize)
    MarkerSize = 6;
end

if nargin<2 || isempty(FontSize)
    FontSize = 5;
end

if nargin<3
    MultiCol = 49;
end


% colors
c1 =     hsv2rgb([.85 1 1]);
c2a =    hsv2rgb([ .13 1 1]);
c2b =    hsv2rgb([.1 1 .6]);
c4a =    hsv2rgb([1 .5 1]);
c4b =    hsv2rgb([1 .3 .9]);
c5a =    hsv2rgb([1/3 1 1]);
c5b =    hsv2rgb([.27 1 .7]);
c6 =     hsv2rgb([ 1 1 1]);
c7a =    hsv2rgb([.55 1 1]);
c7b =    hsv2rgb([.7 .8 1]);
c7c =    hsv2rgb([2/3 1 1]);
cNAa =   hsv2rgb([0 0 1]);
cNAb =   hsv2rgb([0 0 .5]);

% All symbols: +o*.xsd^v<>ph - have them in that order to not get confused
New_symbols = {...
    
    'Xaf1',     c1, '.'; ...
    'Capg',    c1, '.'; ...
    'Cotl1',     c1, '.'; ...
    'Cyfip1',  c1, '.'; ...
    'Pfn1',     c1, '.'; ...
    'Plek',    c1, '.'; ...
    'Cfl1',     c1, '.'; ...   
    'Gsn',   c1, '.'; ...
    'Abi1',   c1, '.'; ...
    'Actr3b',   c1, '.'; ...
    'Baiap2l2',   c1, '.'; ...
    'Arpc2',   c1, '.'; ...
    'Fscn1',   c1, '.'; ...

    'Abi3',      c2a, '.'; ...
    'Cd63',   c2a, '.'; ...
    'Abca7',    c2a, '.'; ...
    'Bin1',    c2a, '.'; ...
    'Apoc2',      c2a, '.'; ...
    'Atp6ap1',     c2a, '.'; ...
    'Atp6v0c',     c2a, '.'; ...
    'Ncf4',     c2a, '.'; ...
    'Rab39',     c2a, '.'; ...
    'Slc2a5',     c2a, '.'; ...
    'Ykt6',     c2a, '.'; ...
    'Atp6v0d2',     c2a, '.'; ...
    'Slc16a3',     c2a, '.'; ...

    'Kcnk13',       c2b, '.'; ...
    'Tmem37',    c2b, '.'; ...
    'Bin2',      c2b, '.'; ...
    'Atp6v0d1',      c2b, '.'; ...
    'Atp6v1d',    c2b, '.'; ...
    
    'Pld4',     c4a, '.'; ...
    'Prune2',     c4a, '.'; ...
    'Nceh1',      c4a, '.'; ...
    'Gusb', c4a, '.'; ...
    'Pld3',   c4a, '.'; ...
    'Cst7',     c4a, '.'; ...
    'Ctss',     c4a, '.'; ...
    'Psmb8',      c4a, '.'; ...
    'Ctsd', c4a, '.'; ...
    'Ctsb',   c4a, '.'; ...
    'Ctsz', c4a, '.'; ...
    'Acaca',   c4a, '.'; ...

    'Dna2',     c4b, '.'; ...
    'Ctsl',     c4b, '.'; ...
    'Atp6ap2',     c4b, '.'; ...
    'Rps6ka1',    c4b, '.';...
    'Nans',     c4b, '.'; ...
    'Mgat1',  c4b, '.'; ...
    'Mbnl1',     c4b, '.'; ...
    'Fam20c',      c4b, '.'; ...
    'Tpi1',   c4b, '.'; ...

    'Nr1h3', c5a, '.'; ...
    'Plcg2',     c5a, '.'; ...
    'Nr1d1',     c5a, '.'; ...
    'Nr1h4',     c5a, '.'; ...
    'Lgmn',     c5a, '.'; ...
    'Tgfbr1',     c5a, '.'; ...
    'Ltf',     c5a, '.'; ...
    'Irf7',    c5a, '.'; ...
    'Tnfrsf1b',   c5a, '.'; ...
    'Gpnmb',   c5a, '.'; ...
    'Il6ra',      c5a, '.'; ...
    'Gnai2',   c5a, '.'; ...
    'Ccr5',   c5a, '.'; ...

    'Grn',   c5b, '.'; ...
    'Fcgr2b',   c5b, '.'; ...
    'Trem2',    c5b, '.'; ...
    'Coro1a',     c5b, '.'; ...
    'Itgb2',     c5b, '.'; ...
    'Cd47',    c5b, '.'; ...
    'Nckap1l',    c5b, '.'; ...
    'Cd33',  c5b, '.'; ...
    'Cd9',    c5b, '.'; ...
    'Hpse',  c5b, '.'; ...
    'Itgax',      c5b, '.'; ...

    'Upk1b',  c6, '.'; ...
    'Cd52',    c6, '.';...
    'Gpr160',    c6, '.'; ...
    'Alox5ap',   c6, '.'; ...
    'Usp18',     c6, '.'; ...
    'Mymk',    c6, '.'; ...
    'Dkk2',    c6, '.'; ...
    'Ecscr',     c6, '.'; ...
    'Rraga',    c6, '.'; ...
    'Egln3',    c6, '.'; ...
    'Hcar2',      c6, '.'; ...
    'Pilra',   c6, '.'; ...
    'Laptm5',     c6, '.'; ...

    'Tmem178',     c7a, '.'; ...
    'Fcrl1',    c7a, '.'; ...
    'H2-Ob',    c7a, '.'; ...
    'H2-DMb2',    c7a, '.'; ...
    'C2',   c7a, '.'; ...
    'C1qb',     c7a, '.';...
    'C1qc',    c7a, '.'; ...
    'Dcstamp',      c7a, '.'; ...
    'Cd300lf',      c7a, '.'; ...
    'H2-DMa',    c7a, '.'; ...
    'C1qa',    c7a, '.'; ...
    'Clec4a2',    c7a, '.'; ...
    'Rsad2',    c7a, '.'; ...

    'Siglece',      c7b, '.'; ...
    'Colec12',   c7b, '.'; ...
    'Cd22',     c7b, '.'; ...
    'Itgam',  c7b, '.'; ...
    'Ccrl2',    c7b, '.'; ...
    'Cxcl13',     c7b, '.'; ...
    'Cxcl16',    c7b, '.'; ...
    'Gbp2',    c7b, '.'; ...
    'Fcgr4',   c7b, '.'; ...
    'Cd79b',    c7b, '.'; ...
    'Cd48',    c7b, '.'; ...
    'Tnfrsf17',   c7b, '.'; ...
    'Cd300lb',   c7b, '.'; ...
    
    'Ifit3',     c7c, '.'; ...
    'Bst2',    c7c, '.'; ...
    'Ifitm6',    c7c, '.'; ...

    'Clec4a3',   cNAa, '.'; ...
    'Clec7a',   cNAa, '.'; ...
    'Cmas',    cNAa, '.'; ...
    'Lgi2',    cNAa, '.'; ...
    'Nr1c1',    cNAa, '.'; ...
    'Nr1c2',   cNAa, '.'; ...
    'Nr1c3',    cNAa, '.'; ...
    'Nr2b1',    cNAa, '.'; ...
    'Nr2b2',   cNAa, '.'; ...
    'Nr2b3',    cNAa, '.'; ...
    'Oasl',    cNAa, '.'; ...
    'Slamf9',   cNAa, '.'; ...
    'Tm2d3',    cNAa, '.'; ...

    'Tmem163',   cNAb, '.'; ...
    'Olfml3',    cNAb, '.'; ...

    };

% delete any existing legend
fc = get(gcf, 'Children');
for i=1:length(fc)
    if strcmp(get(fc(i), 'UserData'), 'key')
        delete(fc(i));
    end
end

MainAxes = gca;

n =  size(New_symbols,1);

gc = get(MainAxes, 'children');
MyChildren = [];
for i=1:length(gc)
    if (strcmp(gc(i).Type, 'line') || strcmp(gc(i).Type, 'scatter')) ...
            && ~isempty(gc(i).DisplayName)
        MyChildren = [MyChildren; i];
    end
end
DisplayNames = {gc(MyChildren).DisplayName};
% get first word of display name as gene
GeneNames = cell(size(DisplayNames));
for i=1:length(DisplayNames)
    GeneNames{i} = strtok(DisplayNames{i});
end
    
clear h s;
j=1;
Present = [];
for i=1:n
    MyGeneName = New_symbols{i,1};
    l = find(strcmp(MyGeneName, GeneNames));
    if ~isempty(l)
        h(j) = gc(MyChildren(l));
		if strcmp(h(j).Type, 'line')
			set(h(j), 'Color', New_symbols{i,2});
        elseif strcmp(h(j).Type, 'scatter')
			set(h(j), 'CData', New_symbols{i,2});
		end
        set(h(j), 'Marker', New_symbols{i,3});

        if MarkerSize>0
			if strcmp(gc(l).Type, 'line')
				set(h(j), 'MarkerSize', MarkerSize);
			elseif strcmp(gc(l).Type, 'scatter')
				set(h(j), 'SizeData', MarkerSize);
			end
        end
        Present(j) = i;
        j=j+1;
    end
end

other_h = setdiff(gc(MyChildren), h);
other_symbols = {other_h.DisplayName};

all_h = [h(:); other_h(:)];
all_sym = {New_symbols{Present,1}, other_symbols{:}};

% lh = legend([h(:); other_h(:)], ...
%     {New_symbols{s,1}, other_symbols{:}}, ...
%     'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
% set(lh, 'color', 'k');
% 
% return;

if MultiCol==0
    lh = legend(all_h, all_sym, 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
    set(lh, 'color', 'k');
else
    ah = axes('Position', [.01 .13 .06 .8]);
    set(ah, 'color', 'k'); cla; hold on; box off
    set(ah, 'UserData', 'key');
    for j=1:length(Present)
        i = Present(j);
        plot(ceil(j/MultiCol)+.1, mod(j-1,MultiCol), New_symbols{i,3}, 'Color', New_symbols{i,2});
        text(ceil(j/MultiCol)+.3, mod(j-1,MultiCol), New_symbols{i,1}, 'color', 'w', 'fontsize', FontSize);
    end
    ylim([-1 MultiCol]);
    set(ah, 'xtick', []);
    set(ah, 'ytick', []);
    set(ah, 'ydir', 'reverse');
end
%     for c=1:nCols
%         rr=((c-1)*50 + 1):min(c*50, length(all_h));
%         if c==1
%             ah(c) = gca;
%             lh(c) = legend(all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'color', 'k');
%             pos(c,:) = get(lh(c), 'position');
%         else
%             ah(c) = axes('position',get(gca,'position'), 'visible','off');
%             lh(c) = legend(ah(c), all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'position', pos(c-1,:) + [1.1 0 0 0]*pos(c-1,3));
%             uistack(lh(c), 'top');
%         end
%     end
%     axes(ah(1));
    
%    error('multicolumn not done yet!');
% end
%     for i=1:nCols
%         first = 1+(i-1)*nCols;
%         last = min(i*nCols,length(all_h));
%         lh = legend(all_h(first:last), ...
%             all_sym{first:last});%, ...
%             %'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
%         set(lh, 'color', 'k');
%     end
set(gcf, 'color', 'k');
set(gcf, 'InvertHardcopy', 'off');
    
axes(MainAxes)
uistack(ah, 'top');

end
