function change_gene_symbols_allgenes_MG3(MarkerSize, FontSize, MultiCol)
% ChangeGeneSymbols(MarkerSize, FontSize, nPerCol);
%
% changes gene symbols so in situ plots look nice. 
% MarkerSize defaults to 6 - if 0, won't change existing sizes
%
% FontSize is font size for legend
%
% nPerCol says how many legend entries per column (0 for one-column)
% 
% Kenneth D. Harris, 29/3/17
% GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.en.html
 
if nargin<1 || isempty(MarkerSize)
    MarkerSize = 6;
end

if nargin<2 || isempty(FontSize)
    FontSize = 5;
end

if nargin<3
    MultiCol = 49;
end


% colors
non_neuron = hsv2rgb([0 0 1]);
pc_or_in =   hsv2rgb([.4 .5 .5]);
less_active =   hsv2rgb([.3 .2 .7]);
pc =        hsv2rgb([1/3 1 1]);
pc2 =       hsv2rgb([.27 1 .7]);
in_general = hsv2rgb([2/3 1 1]);

sst =   hsv2rgb([.55 1 1]);
pvalb = hsv2rgb([.7 .8 1]);
ngf =   hsv2rgb([.85 1 1]);
cnr1 =  hsv2rgb([ 1 1 1]);
vip =   hsv2rgb([ .13 1 1]);
cxcl14= hsv2rgb([.1 1 .6]);

in_all =     hsv2rgb([.57 1 .7]);
ex_all =     hsv2rgb([1/3 1 .7]);
non_neuron_all = hsv2rgb([.59 .1 .7]);

mg_light = hsv2rgb([.1 1 1]);
mg2_light =  hsv2rgb([.85 1 1]);
mg3_light = hsv2rgb([.15 1 1]);
mg4_light = hsv2rgb([1 1 1]);
mg_dark =  hsv2rgb([.1 .6 1]);
mg2_dark =   hsv2rgb([.85 .4 .5]);
mg3_dark =  hsv2rgb([.15 .7 .5]);
mg4_dark =  hsv2rgb([1 .8 .5]);


% All symbols: +o*.xsd^v<>ph - have them in that order to not get confused
New_symbols = {...
    
    'Snca',     in_all, '.'; ...
    'Cplx2',    in_all, '.'; ...
    'Lhx6',     in_all, '.'; ...
    'Col25a1',  in_all, '.'; ...
    'Pnoc',     in_all, '.'; ...
    'Rab3c',    in_all, '.'; ...
    'Gad1',     in_all, '.'; ...   
    'Slc6a1',   in_all, '.'; ...
    
    
    'Th',       in_all, '.'; ...
    'Crhbp',    in_all, '.'; ...
    'Sst',      in_all, '.'; ...
    'Npy',      in_all, '.'; ...
    'Synpr',    in_all, '.'; ...
    'Chodl',    in_all, '.';...
    'Cort',     in_all, '.'; ...
    'Reln',     in_all, '.'; ...
    'Serpini1', in_all, '.'; ...
    'Satb1',    in_all, '.'; ...
    'Grin3a',   in_all, '.'; ...
    
    'Tac1',     in_all, '.'; ...
    'Pvalb',    in_all, '.'; ...
    'Kcnip2',   in_all, '.'; ...
    'Thsd7a',   in_all, '.'; ...
    'Cox6a2',   in_all, '.'; ...
    'Chrm2',    in_all, '.'; ...
    
    'Id2',      in_all, '.'; ...
    'Hapln1',   in_all, '.'; ...
    'Gabrd',    in_all, '.'; ...
    'Cryab',    in_all, '.'; ...
    'Kit',      in_all, '.'; ...
    'Ndnf',     in_all, '.'; ...
    'Nos1',     in_all, '.'; ...
    'Lamp5',    in_all, '.'; ...
    'Cplx3',    in_all, '.'; ...

    'Cadps2',   in_all, '.'; ...
    'Cxcl14',   in_all, '.'; ...
    'Ntng1',    in_all, '.'; ...
    'Cpne5',    in_all, '.'; ...
    'Rgs12',    in_all, '.'; ...
    
% All symbols: +o*.xsd^v<>ph - have them in that order to not get confused

    'Sncg',     in_all, '.'; ...
    'Cnr1',     in_all, '.'; ...
    'Cck',      in_all, '.'; ...
    'Trp53i11', in_all, '.'; ...
    'Sema3c',   in_all, '.'; ...
    'Syt6',     in_all, '.'; ...
    'Yjefn3',   in_all, '.'; ...
    'Rgs10',    in_all, '.'; ...
    'Nov',      in_all, '.'; ...
    'Kctd12',   in_all, '.'; ...
    'Slc17a8',  in_all, '.'; ...
    
    'Tac2',     in_all, '.'; ...
    'Npy2r',    in_all, '.'; ...
    'Calb2',    in_all, '.'; ...
    'Htr3a',    in_all, '.'; ...
    'Slc5a7',   in_all, '.'; ...
    'Penk',     in_all, '.';...
    'Pthlh',    in_all, '.'; ...
    'Vip',      in_all, '.'; ...
    'Crh',      in_all, '.'; ...
    'Qrfpr',    in_all, '.'; ...
    
    
% All symbols: +o*.xsd^v<>ph - have them in that order to not get confused
    'Zcchc12',  in_all, '.'; ...
    'Calb1',    in_all, '.';...
    'Vsnl1',    in_all, '.'; ...
    'Tmsb10',   in_all, '.'; ...
    'Rbp4',     in_all, '.'; ...
    'Fxyd6',    in_all, '.'; ...
    '6330403K07Rik',    in_all, '.'; ...
    'Scg2',     in_all, '.'; ...
    'Gap43',    in_all, '.'; ...
    'Nrsn1',    in_all, '.'; ...
    
        
    'Gda',      ex_all, '.'; ...
    'Bcl11b',   ex_all, '.'; ...
    'Rgs4',     ex_all, '.'; ...
    'Slc24a2',  ex_all, '.'; ...
    'Lphn2',    ex_all, '.'; ...
    'Map2',     ex_all, '.'; ...
    'Prkca',    ex_all, '.'; ...
    'Cdh13',    ex_all, '.'; ...
    'Atp1b1',   ex_all, '.'; ...
    'Pde1a',    ex_all, '.'; ...
    'Calm2',    ex_all, '.'; ...
    'Sema3e',   ex_all, '.'; ...
    

    
    'Nrn1',     ex_all, '.'; ...
    'Pcp4',     ex_all, '.'; ...
    'Rprm',     ex_all, '.'; ...
    'Enpp2',    ex_all, '.';...
    'Rorb',     ex_all, '.'; ...
    'Rasgrf2',  ex_all, '.'; ...
    'Wfs1',     ex_all, '.'; ...
    'Fos',      ex_all, '.'; ...
    'Plcxd2',   ex_all, '.'; ...
    'Crym',     ex_all, '.'; ...
    '3110035E14Rik', ex_all, '.'; ...
    'Foxp2',    ex_all, '.';...
    'Pvrl3',    ex_all, '.'; ...
    
    'Neurod6',  ex_all, '.'; ...
    'Nr4a2',    ex_all, '.'; ...
    'Cux2',     ex_all, '.'; ...
    'Kcnk2',    ex_all, '.'; ...
    'Arpp21',   ex_all, '.'; ...
    'Enc1',     ex_all, '.'; ...
    'Fam19a1',  ex_all, '.'; ...

    
    'Vim',      non_neuron_all, '.'; ...
    'Slc1a2',   non_neuron_all, '.'; ...
    'Pax6',     non_neuron_all, '.'; ...
    'Plp1',     non_neuron_all, '.'; ...
    'Mal',      non_neuron_all, '.'; ...
    'Aldoc',    non_neuron_all, '.'; ...
    'Actb',     non_neuron_all, '.'; ...
    'Sulf2',    non_neuron_all, '.'; ...
    


    'Atp6v0d2', mg_light, '+'; ...
    'Bin1',     mg_light, 'o'; ...
    'Bin2',     mg_light, '*'; ...
    'C1qa',     mg_light, 'x'; ...
    'C1qB',     mg_light, 's'; ...
    'C1qC',     mg_light, 'd'; ...
    'Ccr5',     mg_light, '^'; ...
    'Csf1r',    mg_light, 'v'; ...
    'Cx3cr1',   mg_light, '<'; ...
    'Cyfip1',   mg_light, '>'; ...
    'Grn',      mg_light, 'p'; ...
    'Laptm5',   mg_light, 'h'; ...
    'Olfml3',   mg_dark, '+'; ...
    'P2ry12',   mg_dark, 'o'; ...
    'Plcg2',    mg_dark, '*'; ...
    'Pld3',     mg_dark, 'x'; ...
    'Pld4',     mg_dark, 's'; ...
    'Ptk2b',    mg_dark, 'd'; ...
    'Sparc',    mg_dark, '^'; ...
    'Tmem119',  mg_dark, 'v'; ...

    };

% delete any existing legend
fc = get(gcf, 'Children');
for i=1:length(fc)
    if strcmp(get(fc(i), 'UserData'), 'key')
        delete(fc(i));
    end
end

MainAxes = gca;

n =  size(New_symbols,1);

gc = get(MainAxes, 'children');
MyChildren = [];
for i=1:length(gc)
    if (strcmp(gc(i).Type, 'line') || strcmp(gc(i).Type, 'scatter')) ...
            && ~isempty(gc(i).DisplayName)
        MyChildren = [MyChildren; i];
    end
end
DisplayNames = {gc(MyChildren).DisplayName};
% get first word of display name as gene
GeneNames = cell(size(DisplayNames));
for i=1:length(DisplayNames)
    GeneNames{i} = strtok(DisplayNames{i});
end
    
clear h s;
j=1;
Present = [];
for i=1:n
    MyGeneName = New_symbols{i,1};
    l = find(strcmp(MyGeneName, GeneNames));
    if ~isempty(l)
        h(j) = gc(MyChildren(l));
		if strcmp(h(j).Type, 'line')
			set(h(j), 'Color', New_symbols{i,2});
        elseif strcmp(h(j).Type, 'scatter')
			set(h(j), 'CData', New_symbols{i,2});
		end
        set(h(j), 'Marker', New_symbols{i,3});

        if MarkerSize>0
			if strcmp(gc(l).Type, 'line')
				set(h(j), 'MarkerSize', MarkerSize);
			elseif strcmp(gc(l).Type, 'scatter')
				set(h(j), 'SizeData', MarkerSize);
			end
        end
        Present(j) = i;
        j=j+1;
    end
end

other_h = setdiff(gc(MyChildren), h);
other_symbols = {other_h.DisplayName};

all_h = [h(:); other_h(:)];
all_sym = {New_symbols{Present,1}, other_symbols{:}};

% lh = legend([h(:); other_h(:)], ...
%     {New_symbols{s,1}, other_symbols{:}}, ...
%     'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
% set(lh, 'color', 'k');
% 
% return;

if MultiCol==0
    lh = legend(all_h, all_sym, 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
    set(lh, 'color', 'k');
else
    ah = axes('Position', [.01 .13 .06 .8]);
    set(ah, 'color', 'k'); cla; hold on; box off
    set(ah, 'UserData', 'key');
    for j=1:length(Present)
        i = Present(j);
        plot(ceil(j/MultiCol)+.1, mod(j-1,MultiCol), New_symbols{i,3}, 'Color', New_symbols{i,2});
        text(ceil(j/MultiCol)+.3, mod(j-1,MultiCol), New_symbols{i,1}, 'color', 'w', 'fontsize', FontSize);
    end
    ylim([-1 MultiCol]);
    set(ah, 'xtick', []);
    set(ah, 'ytick', []);
    set(ah, 'ydir', 'reverse');
end
%     for c=1:nCols
%         rr=((c-1)*50 + 1):min(c*50, length(all_h));
%         if c==1
%             ah(c) = gca;
%             lh(c) = legend(all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'color', 'k');
%             pos(c,:) = get(lh(c), 'position');
%         else
%             ah(c) = axes('position',get(gca,'position'), 'visible','off');
%             lh(c) = legend(ah(c), all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'position', pos(c-1,:) + [1.1 0 0 0]*pos(c-1,3));
%             uistack(lh(c), 'top');
%         end
%     end
%     axes(ah(1));
    
%    error('multicolumn not done yet!');
% end
%     for i=1:nCols
%         first = 1+(i-1)*nCols;
%         last = min(i*nCols,length(all_h));
%         lh = legend(all_h(first:last), ...
%             all_sym{first:last});%, ...
%             %'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
%         set(lh, 'color', 'k');
%     end
set(gcf, 'color', 'k');
set(gcf, 'InvertHardcopy', 'off');
    
axes(MainAxes)
uistack(ah, 'top');

end